name = "lit-cloudflare-stream-worker"
type = "javascript"
account_id = "ad689a4c7ee776c5c881c7e04cad097b"
workers_dev = true
compatibility_date = "2021-12-04"

kv_namespaces = [ 
  { binding = "VIDEO_AUTH_META", id = "ed17f1b4fe4e4f149a3ef1d661d8e85e"}
]

[env.production]
zone_id = "bardin-petr.workers.dev"

[build]
command = "yarn && yarn run build"
[build.upload]
format = "modules"
main = "index.mjs"

# [secrets]
# CF_API_TOKEN
# CF_ACCOUNT_ID
# CF_STREAM_PEM
# CF_STREAM_JWK